function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    # precompile(Tuple{ProbabilityDistributions.var"##s76#286",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    precompile(Tuple{typeof(ProbabilityDistributions.∂multivariate_normal_SMLT_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64}})
    # precompile(Tuple{ProbabilityDistributions.var"##s76#196",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    precompile(Tuple{typeof(ProbabilityDistributions.multivariate_normal_SMLT_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64}})
    # precompile(Tuple{ProbabilityDistributions.var"##s25#21",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{ProbabilityDistributions.var"##s76#254",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{ProbabilityDistributions.var"##s24#18",Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{ProbabilityDistributions.var"##s76#164",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{ProbabilityDistributions.var"##s36#110",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{ProbabilityDistributions.var"##s31#24",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    precompile(Tuple{typeof(ProbabilityDistributions.gamma_quote),Int64,Type{Float64},Tuple{Bool,Bool,Bool},Tuple{Bool,Bool,Bool},Bool,Tuple{Bool,Bool,Bool}})
    precompile(Tuple{typeof(ProbabilityDistributions.univariate_normal_quote),Int64,Type{Float64},Bool,Union{Nothing, Bool},Union{Nothing, Bool},Tuple{Bool,Bool,Bool},Tuple{Bool,Bool,Bool},Bool,Bool})
    precompile(Tuple{Type{ProbabilityDistributions.NormalCholeskyConfiguration{Float64}}})
end
