function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    # precompile(Tuple{ProbabilityDistributions.var"##s76#286",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    precompile(Tuple{typeof(ProbabilityDistributions.∂multivariate_normal_SMLT_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64}})
    # precompile(Tuple{ProbabilityDistributions.var"##s76#196",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    precompile(Tuple{typeof(ProbabilityDistributions.multivariate_normal_SMLT_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64}})
    precompile(Tuple{typeof(ProbabilityDistributions.loadδfnmadd_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64},Int64,Int64,Int64,Symbol,Symbol,Symbol,Symbol,Bool,Bool})
    precompile(Tuple{typeof(ProbabilityDistributions.loadδfnmadd_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64},Int64,Int64,Symbol,Symbol,Symbol,Symbol,Symbol,Bool,Bool})
    precompile(Tuple{typeof(ProbabilityDistributions.loadδfnmadd_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64},Symbol,Int64,Int64,Symbol,Symbol,Symbol,Symbol,Bool,Bool,Symbol})
    precompile(Tuple{typeof(ProbabilityDistributions.loadδfnmadd_quote),ProbabilityDistributions.NormalCholeskyConfiguration{Float64},Symbol,Int64,Symbol,Symbol,Symbol,Symbol,Symbol,Bool,Bool,Symbol})
    # precompile(Tuple{ProbabilityDistributions.var"##s25#21",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
    precompile(Tuple{typeof(ProbabilityDistributions.track_mu_store),ProbabilityDistributions.NormalCholeskyConfiguration{Float64},Int,Int,Bool,Int,Int,Bool,Bool,Bool,Int})
    precompile(Tuple{typeof(ProbabilityDistributions.track_mu_store),ProbabilityDistributions.NormalCholeskyConfiguration{Float64},Symbol,Int,Bool,Int,Int,Bool,Bool,Bool,Int})
    # precompile(Tuple{ProbabilityDistributions.var"##s76#254",Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any})
end
